import { Color } from "./color";

export const darkTheme = {
  //color: "#ffffff",
  color: Color.white1,
  bgColor: Color.black6,
  border: "2px solid #505050",
  boxcolor: Color.blue1,
  mode_padding: "0px 0px 3px 0px",
  contextbg: Color.black3,
  contexttx: Color.white1,
  buttoncolor: Color.white4,
  Header_bg: Color.grey9,
  todo_create_bg: Color.grey4,
  contain_status_bg: Color.grey5,
  container_borad_bg: Color.grey4,
  fontColor: Color.black3,
  fontWeight: "700",
  Plus_Button_bg: Color.green3,
};

export const lightTheme = {
  color: Color.black3,
  bgColor: Color.yellow9,
  border: "2px solid #505050",
  boxcolor: Color.blue1,
  mode_rotate: "rotateZ(45deg)",
  mode_padding: "0px 0px 3px 5px",
  listadd_bgColor: Color.black12,
  contextbg: Color.black9,
  contexttx: Color.white1,
  buttoncolor: Color.white4,
  Header_bg: Color.yellow5,
  todo_create_bg: Color.yellow3,
  contain_status_bg: Color.yellow6,
  container_borad_bg: Color.yellow3,
  fontWeight: "700",
  fontColor: Color.white1,
  Plus_Button_bg: Color.orange1,
};
